debug: false
management.endpoints.web.exposure.include: "*"

logging:
    level:
        com.fast.projectboard: debug
        org.springframework.web.servlet: debug
        org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/fastboard
        username: testUsr
        password: ThisIsTestPw!2
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:h2:mem:testdb
#        username: sa
#        driver-class-name: org.h2.Driver
    jpa:
        defer-datasource-initialization: true
        hibernate.ddl-auto: create
        show-sql: true
        properties:
            hibernate.format_sql: true
            hibernate.default_batch_fetch_size: 100
    sql.init.mode: always
    h2:
        console:
            enabled: false
    data.rest:
        base-path: /api
        detection-strategy: annotated